[tool.poetry]
name = "metabasechallenge"
version = "0.1.0"
description = ""
authors = ["Federico Paci <fmpaci88@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mimesis = "^7.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
